services:
  db:
    image: postgres:17-alpine
    container_name: go_postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: my_go_app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go_api_server
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8080"
      DATABASE_URL: "postgres://postgres:postgrespassword@db:5432/my_go_app?sslmode=disable"
      JWT_SECRET: "docker-local-secret-key-12345"
    ports:
      - "8080:8080"

volumes:
  pgdata: